version: '3.8'

services:
  ml-api:
    build: ./attrition-predictor
    container_name: attrition-api
    ports:
      - "8000:8000"
    restart: unless-stopped

  django-erp:
    build: ./erp_project
    container_name: django-erp
    ports:
      - "8080:8080"
    depends_on:
      - ml-api
    environment:
      - ML_API_URL=http://ml-api:8000
    restart: unless-stopped

  mlflow:
    image: python:3.10-slim
    container_name: mlflow-ui
    working_dir: /app
    volumes:
      - ./attrition-predictor:/app
    ports:
      - "5001:5000"
    command: bash -c "pip install mlflow -q && mlflow ui --host 0.0.0.0 --port 5000"
    restart: unless-stopped
